### post signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test6@mail.com",
  "password": "pass"
}

### post signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test6@mail.com",
  "password": "pass"
}

### get current user
GET http://localhost:3000/auth/testMe

### signout
POST http://localhost:3000/auth/signout

### find user by id
GET http://localhost:3000/auth/9

### find all users by email
GET http://localhost:3000/auth?email=Mail

### update user by id
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "email": "new@mail.com"
}

### delete user by id
DELETE http://localhost:3000/auth/2
